# Generated by Django 6.0.5 on 2026-05-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('photo', models.URLField()),
                ('rating', models.FloatField()),
                ('details', models.CharField(max_length=300)),
            ],
        ),
    ]
