# Generated by Django 6.0.5 on 2026-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_dress'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='price',
            field=models.FloatField(default=20000),
            preserve_default=False,
        ),
    ]
